version: '3.8'
services:
  mysql:
    image: mysql:8
    container_name: mysql_todo
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 08147343536Abe
      MYSQL_DATABASE: todo_db
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - "3306:3306"  
    volumes:
      - mysql_data_todo:/var/lib/mysql  
    networks:
      - todo_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p08147343536Abe"]
      interval: 10s
      retries: 5
      start_period: 20s

  todo-app:
    build: .
    container_name: todo_app
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      PORT: 8080
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: appuser
      DB_PASSWORD: apppassword
      DB_NAME: todo_db
    ports:
      - "8080:8080"  
    networks:
      - todo_network

volumes:
  mysql_data_todo:  

networks:
  todo_network:  